<?php

return [
    'titles' => [
        "First, solve the problem. Then, write the code.",
        "Experience is the name everyone gives to their mistakes.",
        "In order to be irreplaceable, one must always be different",
        "Java is to JavaScript what car is to Carpet.",
        "Knowledge is power.",
        "Ruby is rubbish! PHP is phpantastic!",
        "Code is like humor. When you have to explain it, it’s bad.",
        "Fix the cause, not the symptom.",
        "Optimism is an occupational hazard of programming: feedback is the treatment.",
        "Simplicity is the soul of efficiency.",
        "Before software can be reusable it first has to be usable.",
        "Make it work, make it right, make it fast.",
        // "When to use iterative development? You should use iterative development only on projects that you want to succeed.",
        // "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
        // "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
        // "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
    ],
    'quotes' => [
        "I want to stand as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.",
        "And on the subject of burning books: I want to congratulate librarians, not famous for their physical strength or their powerful political connections or their great wealth, who, all over this country, have staunchly resisted anti-democratic bullies who have tried to remove certain books from their shelves, and have refused to reveal to thought police the names of persons who have checked out those titles.",
        "If you want to really hurt you parents, and you don't have the nerve to be gay, the least you can do is go into the arts. I'm not kidding. The arts are not a way to make a living. They are a very human way of making life more bearable. Practicing an art, no matter how well or badly, is a way to make your soul grow, for heaven's sake. Sing in the shower. Dance to the radio. Tell stories. Write a poem to a friend, even a lousy poem. Do it as well as you possible can. You will get an enormous reward. You will have created something.",
        "Hello babies. Welcome to Earth. It's hot in the summer and cold in the winter. It's round and wet and crowded. On the outside, babies, you've got a hundred years here. There's only one rule that I know of, babies-\"God damn it, you've got to be kind.",
        "Here is a lesson in creative writing. First rule: Do not use semicolons. They are transvestite hermaphrodites representing absolutely nothing. All they do is show you've been to college.",
        "And I urge you to please notice when you are happy, and exclaim or murmur or think at some point, 'If this isn't nice, I don't know what is.",
        "And Lot's wife, of course, was told not to look back where all those people and their homes had been. But she did look back, and I love her for that, because it was so human. So she was turned into a pillar of salt. So it goes.",
        "The last thing I ever wanted was to be alive when the three most powerful people on the whole planet would be named Bush, Dick and Colon.",
        "Laughter and tears are both responses to frustration and exhaustion. I myself prefer to laugh, since there is less cleaning do to do afterward.",
        "1492. As children we were taught to memorize this year with pride and joy as the year people began living full and imaginative lives on the continent of North America. Actually, people had been living full and imaginative lives on the continent of North America for hundreds of years before that. 1492 was simply the year sea pirates began to rob, cheat, and kill them.",
        "Many people need desperately to receive this message: 'I feel and think much as you do, care about many of the things you care about, although most people do not care about them. You are not alone."
    ],
    'ctas' => [
        "Sign Up",
        "Sign up for free",
        "Subscribe",
        "Join Free for a Month",
        "Get Started",
        "Give Prezi a try",
        "Our Work",
        "Join",
        "Let's start a new project together",
        "Send Me Specials Now!",
        "Claim Your Free Trial",
        "Continue",
        "Countdown Clock",
        "What We Do",
        "Launch (Do Not Press)",
        "Find out when we have more",
        "Follow the Magic",
        "Sign up to drive",
        "Go Premium",
        "Send me the coupons",
        "Continue with Facebook",
        "Take me there",
        "Download on the App Store",
        "Get Started",
        "Find out more",
        "View Full-Time Courses",
        "Give by Credit Card",
        "Flights",
        "Grab the template!",
        "Get Started for Free",
        "Get involved",
        "Limited Edition",
        "Shop the Lookbook",
        "3 months free",
        "Shop Now",
        "Learn More",
        "Compare Features"
    ]
];